import Navigation from "@/_components/Navigation";
import "./globals.css";
import "@fontsource-variable/nunito"
import Footer from "@/_components/Footer";
import MobileNavigation from "@/_components/MobileNavigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <MobileNavigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
